<?php

ClassLoader::addNamespace( 'CatalogManager' );

ClassLoader::addClasses([

    'CatalogManager\tl_page' => 'system/modules/catalog-manager/classes/tl_page.php',
    'CatalogManager\Map' => 'system/modules/catalog-manager/library/alnv/Fields/Map.php',
    'CatalogManager\tl_module' => 'system/modules/catalog-manager/classes/tl_module.php',
    'CatalogManager\Toolkit' => 'system/modules/catalog-manager/library/alnv/Toolkit.php',
    'CatalogManager\tl_catalog' => 'system/modules/catalog-manager/classes/tl_catalog.php',
    'CatalogManager\Text' => 'system/modules/catalog-manager/library/alnv/Fields/Text.php',
    'CatalogManager\tl_settings' => 'system/modules/catalog-manager/classes/tl_settings.php',
    'CatalogManager\Radio' => 'system/modules/catalog-manager/library/alnv/Fields/Radio.php',
    'CatalogManager\Select' => 'system/modules/catalog-manager/library/alnv/Fields/Select.php',
    'CatalogManager\Hidden' => 'system/modules/catalog-manager/library/alnv/Fields/Hidden.php',
    'CatalogManager\Upload' => 'system/modules/catalog-manager/library/alnv/Fields/Upload.php',
    'CatalogManager\Number' => 'system/modules/catalog-manager/library/alnv/Fields/Number.php',
    'CatalogManager\IconGetter' => 'system/modules/catalog-manager/library/alnv/IconGetter.php',
    'CatalogManager\CSVBuilder' => 'system/modules/catalog-manager/library/alnv/CSVBuilder.php',
    'CatalogManager\SQLBuilder' => 'system/modules/catalog-manager/library/alnv/SQLBuilder.php',
    'CatalogManager\DCABuilder' => 'system/modules/catalog-manager/library/alnv/DCABuilder.php',
    'CatalogManager\CatalogView' => 'system/modules/catalog-manager/library/alnv/CatalogView.php',
    'CatalogManager\Checkbox' => 'system/modules/catalog-manager/library/alnv/Fields/Checkbox.php',
    'CatalogManager\Textarea' => 'system/modules/catalog-manager/library/alnv/Fields/Textarea.php',
    'CatalogManager\GeoCoding' => 'system/modules/catalog-manager/library/alnv/Maps/GeoCoding.php',
    'CatalogManager\DCACallbacks' => 'system/modules/catalog-manager/library/alnv/DCACallbacks.php',
    'CatalogManager\DateInput' => 'system/modules/catalog-manager/library/alnv/Fields/DateInput.php',
    'CatalogManager\DCAPermission' => 'system/modules/catalog-manager/library/alnv/DCAPermission.php',
    'CatalogManager\OptionsGetter' => 'system/modules/catalog-manager/library/alnv/OptionsGetter.php',
    'CatalogManager\CatalogFilter' => 'system/modules/catalog-manager/library/alnv/CatalogFilter.php',
    'CatalogManager\SQLQueryHelper' => 'system/modules/catalog-manager/library/alnv/SQLQueryHelper.php',
    'CatalogManager\TemplateHelper' => 'system/modules/catalog-manager/library/alnv/TemplateHelper.php',
    'CatalogManager\tl_catalog_fields' => 'system/modules/catalog-manager/classes/tl_catalog_fields.php',
    'CatalogManager\SQLQueryBuilder' => 'system/modules/catalog-manager/library/alnv/SQLQueryBuilder.php',
    'CatalogManager\FrontendEditing' => 'system/modules/catalog-manager/library/alnv/FrontendEditing.php',
    'CatalogManager\MessageInput' => 'system/modules/catalog-manager/library/alnv/Fields/MessageInput.php',
    'CatalogManager\DCABuilderHelper' => 'system/modules/catalog-manager/library/alnv/DCABuilderHelper.php',
    'CatalogManager\CatalogController' => 'system/modules/catalog-manager/library/alnv/CatalogController.php',
    'CatalogManager\SearchIndexBuilder' => 'system/modules/catalog-manager/library/alnv/SearchIndexBuilder.php',
    'CatalogManager\ReviseRelatedTables' => 'system/modules/catalog-manager/library/alnv/ReviseRelatedTables.php',
    'CatalogManager\ModuleMasterView' => 'system/modules/catalog-manager/library/alnv/Modules/ModuleMasterView.php',
    'CatalogManager\ActiveInsertTag' => 'system/modules/catalog-manager/library/alnv/Inserttags/ActiveInsertTag.php',
    'CatalogManager\MasterInsertTag' => 'system/modules/catalog-manager/library/alnv/Inserttags/MasterInsertTag.php',
    'CatalogManager\CatalogMessageForm' => 'system/modules/catalog-manager/library/alnv/Forms/CatalogMessageForm.php',
    'CatalogManager\I18nCatalogTranslator' => 'system/modules/catalog-manager/library/alnv/I18nCatalogTranslator.php',
    'CatalogManager\ChangeLanguageExtension' => 'system/modules/catalog-manager/library/alnv/ChangeLanguageExtension.php',
    'CatalogManager\ModuleUniversalView' => 'system/modules/catalog-manager/library/alnv/Modules/ModuleUniversalView.php',
    'CatalogManager\UserPermissionExtension' => 'system/modules/catalog-manager/library/alnv/UserPermissionExtension.php',
    'CatalogManager\ModuleCatalogFilter' => 'system/modules/catalog-manager/library/alnv/Modules/ModuleCatalogFilter.php',
    'CatalogManager\CatalogMessageWidget' => 'system/modules/catalog-manager/library/alnv/Widgets/CatalogMessageWidget.php',
    'CatalogManager\CatalogOrderByWizard' => 'system/modules/catalog-manager/library/alnv/Widgets/CatalogOrderByWizard.php',
    'CatalogManager\CatalogTaxonomyWizard' => 'system/modules/catalog-manager/library/alnv/Widgets/CatalogTaxonomyWizard.php',
    'CatalogManager\MemberPermissionExtension' => 'system/modules/catalog-manager/library/alnv/MemberPermissionExtension.php',
    'CatalogManager\FrontendEditingPermission' => 'system/modules/catalog-manager/library/alnv/FrontendEditingPermission.php',
    'CatalogManager\CatalogManagerInitializer' => 'system/modules/catalog-manager/library/alnv/CatalogManagerInitializer.php',
    'CatalogManager\CatalogRelationWizard' => 'system/modules/catalog-manager/library/alnv/Widgets/CatalogRelationWizard.php',
    'CatalogManager\CatalogManagerVerification' => 'system/modules/catalog-manager/library/alnv/CatalogManagerVerification.php',
    'CatalogManager\CatalogFilterFieldSelectWizard' => 'system/modules/catalog-manager/library/alnv/Widgets/CatalogFilterFieldSelectWizard.php'
]);

TemplateLoader::addFiles([

    'ctlg_field_map' => 'system/modules/catalog-manager/templates',
    'ctlg_view_teaser' => 'system/modules/catalog-manager/templates',
    'ctlg_view_master' => 'system/modules/catalog-manager/templates',
    'ctlg_map_default' => 'system/modules/catalog-manager/templates',
    'ctlg_form_default' => 'system/modules/catalog-manager/templates',
    'ctlg_form_grouped' => 'system/modules/catalog-manager/templates',
    'ctlg_message_field' => 'system/modules/catalog-manager/templates',
    'mod_catalog_filter' => 'system/modules/catalog-manager/templates',
    'mod_catalog_master' => 'system/modules/catalog-manager/templates',
    'ctlg_debug_default' => 'system/modules/catalog-manager/templates',
    'mod_catalog_universal' => 'system/modules/catalog-manager/templates',
    'mod_catalog_map_default' => 'system/modules/catalog-manager/templates'
]);